dataset: "tfinance"


LA-SAGE-S: # in tmux 7 gpu 2 multi run: 0.9710 / 0.0023  
  add_self_loop: false
  agg: 'mean'
  batch_size: 256

  dataset_seed: 717
  dropout: 0.4
  epochs: 500
  eval_interval: 1
  flush_seconds: 60
  force_reload: false
  full_neighbors: true
  hid_dim: 64
  homo: true

  lr: 0.005
  lr_scheduler: false

  monitor: 'auc_gnn'
  
  n_layer: 1
  no_dev: false
  norm_feat: true
  num_trans: 1
  num_workers: 8
  optimizer: 'Adam'
  patience: 100
  proj: true
  reduction: 'mean'
  relation_agg: 'cat'
  resi: 0.2
  run_best: false
  sampled_neighbors: [-1, -1, -1]

  sampling_type: 'in'
  seed: 1234
  test_each_epoch: false
  thres: 0.5
  threshold_moving: true
  train_size: 0.4
  val_size: 0.2
  weight_decay: 0.0
  weighted_loss: false


# LA-SAGE-S: # in tmux 10 gpu 3 multi run: AUC 0.9692 / 0.0032  MF1: 0.9203 / 0.0028 GMean: 0.8853 / 0.0083
#   add_self_loop: false
#   agg: 'mean'
#   batch_size: 128

#   dataset_seed: 717
#   dropout: 0.3
#   epochs: 300
#   eval_interval: 1
#   flush_seconds: 60
#   force_reload: false
#   full_neighbors: true
#   hid_dim: 128
#   homo: true

#   lr: 0.001
#   lr_scheduler: false

#   monitor: 'auc_gnn'
  
#   mlp_activation: 'elu'
#   n_layer: 1
#   no_dev: false
#   norm_feat: true
#   num_trans: 2
#   num_workers: 8
#   optimizer: 'Adam'
#   patience: 100
#   proj: true
#   reduction: 'mean'
#   relation_agg: 'cat'
#   resi: 0.2
#   run_best: false
#   sampled_neighbors: [-1, -1, -1]

#   sampling_type: 'in'
#   seed: 1234
#   test_each_epoch: false
#   thres: 0.5
#   threshold_moving: true
#   train_size: 0.4
#   val_size: 0.2
#   weight_decay: 0.00005
#   weighted_loss: false


